tangosite/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name = 'post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share,  name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list,  name='post_list_by_tag')
]

tangosite/pages/urls.py
from django.urls import path
from .views import HomePageView,  AboutPageView

app_name = 'pages'


urlpatterns = [
    # path('', views.index, name='index'),
    path('', HomePageView.as_view(), name=('homepage')),
    path('about/', AboutPageView.as_view(), name=('about'))
]   

tangosite/tangosite/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from blog.views import index
# from pages.views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('pages/', include('pages.urls')),
    path('', index, name = 'index'),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tangosite/blog/models.py
from django.db import models
from django.db.models.base import ModelState
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year,
                                                 self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created', )

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

tangosite/pages/models.py
from django.db import models

# Create your models here.

tangosite/blog/forms.py
from django import forms
from django.db import models
from django.forms import fields
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

tangosite/blog/views.py
from django import forms
from django.core import paginator
from django.core.checks import messages
from django.shortcuts import render,  get_object_or_404
from django.urls.base import is_valid_path
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm,  CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


def index(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }

    return render(request, 'blog/index.html', context)


# class PostListView(ListView):
#     queryset = Post.objects.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # from 3 page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'page': page,
        'tag': tag
    }
    return render(request, 'blog/post/list.html', context)


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,  status='published',
                             publish__year=year, publish__month=month, publish__day=day)
    # list of active coment for this article
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # User have been sent comment'
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # creating form without saving
            new_comment = comment_form.save(commit=False)
            # linking the comment to the current article
            new_comment.post = post
            # save comment in database
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]
    context = {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
    }
    return render(request, 'blog/post/detail.html', context)


def post_share(request, post_id):
    # getting an   article by id
    post = get_object_or_404(Post, id=post_id,  status='published')
    sent = False
    if request.method == 'POST':
        # the form was sent for saving
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # all fields  of the form have been validated
            cd = form.cleaned_data
            # sending  e-mail
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        'post': post,
        'form': form,
        'sent': sent,
    }
    return render(request, 'blog/post/share.html', context)

tangosite/pages/views.py
from typing import ClassVar
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class HomePageView(TemplateView):
    template_name = 'pages/index.html' 

class AboutPageView(TemplateView):
    template_name = 'pages/about.html'



def index(request):
    return render(request, 'pages/index.html')

tangosite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'blog/post/css/index.css' %}"> -->
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header_inner">
                <div class="header_logo">Rango</div>
                <nav class="nav">
                    <a class="nav_link" href="{% url 'blog:post_list' %}">Blog</a>
                    <a class="nav_link" href="#">Portfolio</a>
                    <a class="nav_link" href="#">Contact</a>
                </nav>
            </div>
        </div>
    </header>
    {% block intro %}{% endblock %}
    <div class="content">
        <div class="container">
    {% block content %}{% endblock %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

tangosite/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static  %}
{% block title %}My blog{% endblock %}
{% block intro %}
<div class="intro">
    <div class="container">
        <div class="intro_inner">
            <h1 class="intro_title">Welcome the ranch</h1>
        </div>
    </div>
</div>

{%endblock%}

tangosite/blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}.
        </span>
        {% if page.has_next %}
        <a href="?page={{page.next_page_number}}">Next</a>
        {% endif %}
    </span>
</div>

tangosite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}"> Share this post</a>
    </p>
    <p class="similar-posts">Similar posts:
        {% for post in similar_posts %}
        <ul>
            <li>
                <a href="{{ post.get_absolute_url}}">
                    {{post.title}}
                </a>
            </li>
        </ul>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment {{ total_comments|pluralize}}</h2>
    {% endwith %}
    {% for comment in comments  %}
        <div class="comment">
            <p class="info">
                Comment {{farloop.counter}} by {{comment.name}}
                {{comment.created}}
            </p>
            {{comment.body|linebreaks}}
        </div>
        {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
    <h2>Your  comment has been added.</h2>
    {% else %}
    <h2>Add a new comment </h2>
    <form action="." method='post' >
        {{comment_form.as_p}}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>
    {% endif %}
{% endblock %}

tangosite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load static  %}
{% block title %}My blog{% endblock %}

{% block  content %}

    <h1>Blog news</h1>
    {% if tag %}
    <h2>Posts tagged with "{{tag.name}}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{  post.get_absolute_url }}"> {{post.title}} </a>
        </h2>
        <p class="tags">Tags:
            {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                {{tag.name}}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>

        {{post.body|truncatewords:30|linebreaks}}
        <p class="date" >{{post.publish}} by {{post.author}}</p>

    {% endfor %}
    {% include "blog/pagination.html" with page=posts %}

{% endblock %}

tangosite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}{% endblock %}

{% block  content %}
    {%  if sent %}
        <h1>E-mail succcessfully sent </h1>
        <p>"{{post.title}}" was succcessfully sent to {{form.cleaned_data.to}}</p>
    {% else %}
        <h1> Share "{{post.title}}" by e-mail</h1>
        <form action="." method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

tangosite/pages/templates/base.html
<header>
    <a href="{% url 'pages:homepage' %}">home</a>
    <a href="{% url 'pages:about' %}">about</a>


</header>
{% block content %}
{% endblock content %}

tangosite/pages/templates/pages/about.html
{% extends 'base.html' %}

{% block content %}
    about pages
{% endblock %}

tangosite/pages/templates/pages/index.html
{% extends 'base.html' %}


{% block content %}
page!
{% endblock content %}